### PR TITLE
Feature Implement Object Store Commands

### PR DESCRIPTION
**Pull request by rjra2611**
- Adds `lean object-store` commands: `get`/`set`/`list`/`delete`
- Adds `lean cloud object-store` commands: `get`/`set`/`list`/`delete`
- Update readme
- Add tests

Cloud Object Store Commands
---
image

Tests ( list -> set -> get -> list -> delete -> list ) (Outdated, commands shifted under `lean cloud` group)
---

image

image

image

image

image

image

image

image

image

Local Object Store Commands
---

image

Tests - Local Object store commands
---

animation

### CODE REVIEW

**Comment by jaredbroad** [comment]
Can you please alias get -> ls

**Comment by rjra2611** [comment]
> Can you please alias get -> ls

image

**Review by Martin-Molinero — COMMENTED** [review]
Nice! ty, shared review through slack 👍

**Review by Martin-Molinero — APPROVED** [review]
Looks good! ty 🚀

**Review by jaredbroad — APPROVED** [review]

**Pull request merged**
